# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppGUI.ui',
# licensing of 'AppGUI.ui' applies.
#
# Created: Tue Jun 21 11:07:53 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Cleanliness_Check(object):
    def setupUi(self, Cleanliness_Check):
        Cleanliness_Check.setObjectName("Khoanh Vùng Tự Động")
        Cleanliness_Check.resize(1410, 710)
        Cleanliness_Check.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Cleanliness_Check)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QListWidget::item:hover{\n"
"    color: blue;\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    border: 2px solid blue;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"}\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.fileTab = QtWidgets.QWidget()
        self.fileTab.setObjectName("fileTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fileTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fileList = QtWidgets.QListWidget(self.fileTab)
        self.fileList.setMovement(QtWidgets.QListView.Static)
        self.fileList.setFlow(QtWidgets.QListView.LeftToRight)
        self.fileList.setProperty("isWrapping", False)
        self.fileList.setSpacing(20)
        self.fileList.setViewMode(QtWidgets.QListView.IconMode)
        self.fileList.setObjectName("fileList")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/svgBlack/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.fileList)
        item.setIcon(icon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/svgBlack/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.fileList)
        item.setIcon(icon1)
        self.gridLayout_2.addWidget(self.fileList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fileTab, icon, "")
        self.cropTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cropTab.setFont(font)
        self.cropTab.setObjectName("cropTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cropTab)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cropList = QtWidgets.QListWidget(self.cropTab)
        self.cropList.setMovement(QtWidgets.QListView.Static)
        self.cropList.setFlow(QtWidgets.QListView.LeftToRight)
        self.cropList.setProperty("isWrapping", False)
        self.cropList.setSpacing(20)
        self.cropList.setViewMode(QtWidgets.QListView.IconMode)
        self.cropList.setObjectName("cropList")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/svgBlack/rectangle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/svgBlack/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/svgBlack/tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/svgBlack/ok-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/svgBlack/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon6)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/svgBlack/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon7)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/svgBlack/forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.cropList)
        item.setIcon(icon8)
        self.verticalLayout_3.addWidget(self.cropList)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/svgBlack/crop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.cropTab, icon9, "")
        self.generateTab = QtWidgets.QWidget()
        self.generateTab.setObjectName("generateTab")
        self.generateList = QtWidgets.QListWidget(self.generateTab)
        self.generateList.setGeometry(QtCore.QRect(0, 0, 1401, 121))
        self.generateList.setMovement(QtWidgets.QListView.Static)
        self.generateList.setProperty("isWrapping", False)
        self.generateList.setSpacing(20)
        self.generateList.setViewMode(QtWidgets.QListView.IconMode)
        self.generateList.setObjectName("generateList")
        item = QtWidgets.QListWidgetItem(self.generateList)
        item.setIcon(icon4)
        item = QtWidgets.QListWidgetItem(self.generateList)
        item.setIcon(icon5)
        item = QtWidgets.QListWidgetItem(self.generateList)
        item.setIcon(icon7)
        item = QtWidgets.QListWidgetItem(self.generateList)
        item.setIcon(icon8)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/svgBlack/cards.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.generateTab, icon10, "")
        self.superResolutionTab = QtWidgets.QWidget()
        self.superResolutionTab.setObjectName("superResolutionTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.superResolutionTab)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.superResolutionList = QtWidgets.QListWidget(self.superResolutionTab)
        self.superResolutionList.setMovement(QtWidgets.QListView.Static)
        self.superResolutionList.setProperty("isWrapping", False)
        self.superResolutionList.setSpacing(20)
        self.superResolutionList.setViewMode(QtWidgets.QListView.IconMode)
        self.superResolutionList.setObjectName("superResolutionList")
        item = QtWidgets.QListWidgetItem(self.superResolutionList)
        item.setIcon(icon4)
        item = QtWidgets.QListWidgetItem(self.superResolutionList)
        item.setIcon(icon5)
        item = QtWidgets.QListWidgetItem(self.superResolutionList)
        item.setIcon(icon6)
        item = QtWidgets.QListWidgetItem(self.superResolutionList)
        item.setIcon(icon7)
        item = QtWidgets.QListWidgetItem(self.superResolutionList)
        item.setIcon(icon8)
        self.verticalLayout_4.addWidget(self.superResolutionList)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/svgBlack/verified.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.superResolutionTab, icon11, "")
        self.SegmentTab = QtWidgets.QWidget()
        self.SegmentTab.setObjectName("SegmentTab")
        self.segmentList = QtWidgets.QListWidget(self.SegmentTab)
        self.segmentList.setGeometry(QtCore.QRect(0, 0, 1401, 106))
        self.segmentList.setMovement(QtWidgets.QListView.Static)
        self.segmentList.setProperty("isWrapping", False)
        self.segmentList.setSpacing(20)
        self.segmentList.setViewMode(QtWidgets.QListView.IconMode)
        self.segmentList.setObjectName("segmentList")
        item = QtWidgets.QListWidgetItem(self.segmentList)
        item.setIcon(icon4)
        item = QtWidgets.QListWidgetItem(self.segmentList)
        item.setIcon(icon5)
        item = QtWidgets.QListWidgetItem(self.segmentList)
        item.setIcon(icon6)
        item = QtWidgets.QListWidgetItem(self.segmentList)
        item.setIcon(icon7)
        item = QtWidgets.QListWidgetItem(self.segmentList)
        item.setIcon(icon8)
        self.tabWidget.addTab(self.SegmentTab, "")
        self.evaluateTab = QtWidgets.QWidget()
        self.evaluateTab.setObjectName("evaluateTab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.evaluateTab)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.evaluateList = QtWidgets.QListWidget(self.evaluateTab)
        self.evaluateList.setMovement(QtWidgets.QListView.Static)
        self.evaluateList.setProperty("isWrapping", False)
        self.evaluateList.setSpacing(20)
        self.evaluateList.setViewMode(QtWidgets.QListView.IconMode)
        self.evaluateList.setObjectName("evaluateList")
        item = QtWidgets.QListWidgetItem(self.evaluateList)
        item.setIcon(icon4)
        item = QtWidgets.QListWidgetItem(self.evaluateList)
        item.setIcon(icon5)
        item = QtWidgets.QListWidgetItem(self.evaluateList)
        item.setIcon(icon6)
        item = QtWidgets.QListWidgetItem(self.evaluateList)
        item.setIcon(icon7)
        item = QtWidgets.QListWidgetItem(self.evaluateList)
        item.setIcon(icon8)
        self.verticalLayout_21.addWidget(self.evaluateList)
        self.tabWidget.addTab(self.evaluateTab, "")
        self.cleanlinessTab = QtWidgets.QWidget()
        self.cleanlinessTab.setObjectName("cleanlinessTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cleanlinessTab)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cleanlinessList = QtWidgets.QListWidget(self.cleanlinessTab)
        self.cleanlinessList.setMovement(QtWidgets.QListView.Static)
        self.cleanlinessList.setFlow(QtWidgets.QListView.LeftToRight)
        self.cleanlinessList.setProperty("isWrapping", False)
        self.cleanlinessList.setSpacing(20)
        self.cleanlinessList.setViewMode(QtWidgets.QListView.IconMode)
        self.cleanlinessList.setObjectName("cleanlinessList")
        item = QtWidgets.QListWidgetItem(self.cleanlinessList)
        item.setIcon(icon4)
        item = QtWidgets.QListWidgetItem(self.cleanlinessList)
        item.setIcon(icon5)
        item = QtWidgets.QListWidgetItem(self.cleanlinessList)
        item.setIcon(icon6)
        item = QtWidgets.QListWidgetItem(self.cleanlinessList)
        item.setIcon(icon7)
        item = QtWidgets.QListWidgetItem(self.cleanlinessList)
        item.setIcon(icon8)
        self.verticalLayout_6.addWidget(self.cleanlinessList)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/svgBlack/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.cleanlinessTab, icon12, "")
        self.dicomTab = QtWidgets.QWidget()
        self.dicomTab.setObjectName("dicomTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dicomTab)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dicomList = QtWidgets.QListWidget(self.dicomTab)
        self.dicomList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dicomList.setMovement(QtWidgets.QListView.Static)
        self.dicomList.setFlow(QtWidgets.QListView.LeftToRight)
        self.dicomList.setProperty("isWrapping", False)
        self.dicomList.setSpacing(20)
        self.dicomList.setViewMode(QtWidgets.QListView.IconMode)
        self.dicomList.setObjectName("dicomList")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/svgBlack/link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.dicomList)
        item.setIcon(icon13)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/svgBlack/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.dicomList)
        item.setIcon(icon14)
        item = QtWidgets.QListWidgetItem(self.dicomList)
        item.setIcon(icon8)
        self.verticalLayout_7.addWidget(self.dicomList)
        self.tabWidget.addTab(self.dicomTab, icon14, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeView = QtWidgets.QTreeView(self.widget)
        self.treeView.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeView.setFont(font)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_4.addWidget(self.treeView)
        self.content = QtWidgets.QWidget(self.widget)
        self.content.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.content.setObjectName("content")
        self.gridLayout = QtWidgets.QGridLayout(self.content)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(self.content)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xStart = QtWidgets.QSpinBox(self.widget_4)
        self.xStart.setMaximum(9999)
        self.xStart.setProperty("value", 0)
        self.xStart.setObjectName("xStart")
        self.horizontalLayout_3.addWidget(self.xStart)
        self.frame_2 = QtWidgets.QFrame(self.widget_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SR2 = QtWidgets.QRadioButton(self.frame_2)
        self.SR2.setObjectName("SR2")
        self.horizontalLayout_2.addWidget(self.SR2)
        self.SR4 = QtWidgets.QRadioButton(self.frame_2)
        self.SR4.setObjectName("SR4")
        self.horizontalLayout_2.addWidget(self.SR4)
        self.SR8 = QtWidgets.QRadioButton(self.frame_2)
        self.SR8.setObjectName("SR8")
        self.horizontalLayout_2.addWidget(self.SR8)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.xEnd = QtWidgets.QSpinBox(self.widget_4)
        self.xEnd.setMaximum(9999)
        self.xEnd.setObjectName("xEnd")
        self.horizontalLayout_3.addWidget(self.xEnd)
        self.gridLayout.addWidget(self.widget_4, 0, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.content)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.yStart = QtWidgets.QSpinBox(self.widget_5)
        self.yStart.setMaximum(9999)
        self.yStart.setObjectName("yStart")
        self.verticalLayout_12.addWidget(self.yStart)
        self.frame = QtWidgets.QFrame(self.widget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12.addWidget(self.frame)
        self.yEnd = QtWidgets.QSpinBox(self.widget_5)
        self.yEnd.setMaximum(9999)
        self.yEnd.setObjectName("yEnd")
        self.verticalLayout_12.addWidget(self.yEnd)
        self.gridLayout.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.content)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_1 = QtWidgets.QFrame(self.widget_3)
        self.frame_1.setAutoFillBackground(True)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_20 = QtWidgets.QFrame(self.frame_1)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_29 = QtWidgets.QLabel(self.frame_20)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout.addWidget(self.label_29)
        self.worstx2 = QtWidgets.QRadioButton(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.worstx2.setFont(font)
        self.worstx2.setObjectName("worstx2")
        self.verticalLayout.addWidget(self.worstx2)
        self.poorx2 = QtWidgets.QRadioButton(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poorx2.setFont(font)
        self.poorx2.setObjectName("poorx2")
        self.verticalLayout.addWidget(self.poorx2)
        self.goodx2 = QtWidgets.QRadioButton(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.goodx2.setFont(font)
        self.goodx2.setObjectName("goodx2")
        self.verticalLayout.addWidget(self.goodx2)
        self.betterx2 = QtWidgets.QRadioButton(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.betterx2.setFont(font)
        self.betterx2.setObjectName("betterx2")
        self.verticalLayout.addWidget(self.betterx2)
        self.excellentx2 = QtWidgets.QRadioButton(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.excellentx2.setFont(font)
        self.excellentx2.setObjectName("excellentx2")
        self.verticalLayout.addWidget(self.excellentx2)
        self.gridLayout_4.addWidget(self.frame_20, 0, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_1)
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_38 = QtWidgets.QLabel(self.frame_21)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_2.addWidget(self.label_38)
        self.descriptionx2 = QtWidgets.QTextEdit(self.frame_21)
        self.descriptionx2.setObjectName("descriptionx2")
        self.verticalLayout_2.addWidget(self.descriptionx2)
        self.gridLayout_4.addWidget(self.frame_21, 0, 1, 2, 1)
        self.horizontalLayout_5.addWidget(self.frame_1)
        self.frame_6 = QtWidgets.QFrame(self.widget_3)
        self.frame_6.setAutoFillBackground(True)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_22 = QtWidgets.QFrame(self.frame_6)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_30 = QtWidgets.QLabel(self.frame_22)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        self.worstx4 = QtWidgets.QRadioButton(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.worstx4.setFont(font)
        self.worstx4.setObjectName("worstx4")
        self.verticalLayout_5.addWidget(self.worstx4)
        self.poorx4 = QtWidgets.QRadioButton(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poorx4.setFont(font)
        self.poorx4.setObjectName("poorx4")
        self.verticalLayout_5.addWidget(self.poorx4)
        self.goodx4 = QtWidgets.QRadioButton(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.goodx4.setFont(font)
        self.goodx4.setObjectName("goodx4")
        self.verticalLayout_5.addWidget(self.goodx4)
        self.betterx4 = QtWidgets.QRadioButton(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.betterx4.setFont(font)
        self.betterx4.setObjectName("betterx4")
        self.verticalLayout_5.addWidget(self.betterx4)
        self.excellentx4 = QtWidgets.QRadioButton(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.excellentx4.setFont(font)
        self.excellentx4.setObjectName("excellentx4")
        self.verticalLayout_5.addWidget(self.excellentx4)
        self.gridLayout_6.addWidget(self.frame_22, 0, 0, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.frame_6)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_39 = QtWidgets.QLabel(self.frame_23)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_8.addWidget(self.label_39)
        self.descriptionx4 = QtWidgets.QTextEdit(self.frame_23)
        self.descriptionx4.setObjectName("descriptionx4")
        self.verticalLayout_8.addWidget(self.descriptionx4)
        self.gridLayout_6.addWidget(self.frame_23, 0, 1, 2, 1)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_14.addWidget(self.widget_3)
        self.btnNextx4 = QtWidgets.QPushButton(self.widget_2)
        self.btnNextx4.setObjectName("btnNextx4")
        self.verticalLayout_14.addWidget(self.btnNextx4)
        self.gridLayout.addWidget(self.widget_2, 2, 1, 1, 1)
        self.container = QtWidgets.QWidget(self.content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.container)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sourceImage = QtWidgets.QLabel(self.frame_3)
        self.sourceImage.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceImage.setObjectName("sourceImage")
        self.verticalLayout_9.addWidget(self.sourceImage)
        self.gVSource = QtWidgets.QGraphicsView(self.frame_3)
        self.gVSource.setObjectName("gVSource")
        self.verticalLayout_9.addWidget(self.gVSource)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.container)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.destinationImage = QtWidgets.QLabel(self.frame_4)
        self.destinationImage.setAlignment(QtCore.Qt.AlignCenter)
        self.destinationImage.setObjectName("destinationImage")
        self.verticalLayout_10.addWidget(self.destinationImage)
        self.gVx2 = QtWidgets.QGraphicsView(self.frame_4)
        self.gVx2.setEnabled(True)
        self.gVx2.setObjectName("gVx2")
        self.verticalLayout_10.addWidget(self.gVx2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.container)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.destinationImage_2 = QtWidgets.QLabel(self.frame_5)
        self.destinationImage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.destinationImage_2.setObjectName("destinationImage_2")
        self.verticalLayout_11.addWidget(self.destinationImage_2)
        self.gVx4 = QtWidgets.QGraphicsView(self.frame_5)
        self.gVx4.setObjectName("gVx4")
        self.verticalLayout_11.addWidget(self.gVx4)
        self.horizontalLayout.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.container, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.content)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        Cleanliness_Check.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cleanliness_Check)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Cleanliness_Check)

    def retranslateUi(self, Cleanliness_Check):
        Cleanliness_Check.setWindowTitle(QtWidgets.QApplication.translate("Cleanliness_Check", "MainWindow", None, -1))
        __sortingEnabled = self.fileList.isSortingEnabled()
        self.fileList.setSortingEnabled(False)
        self.fileList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Open file", None, -1))
        self.fileList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Open folder", None, -1))
        self.fileList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fileTab), QtWidgets.QApplication.translate("Cleanliness_Check", "File", None, -1))
        __sortingEnabled = self.cropList.isSortingEnabled()
        self.cropList.setSortingEnabled(False)
        self.cropList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Cut Infor", None, -1))
        self.cropList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Use Mask", None, -1))
        self.cropList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Config", None, -1))
        self.cropList.item(3).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Apply", None, -1))
        self.cropList.item(4).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Reset", None, -1))
        self.cropList.item(5).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Save", None, -1))
        self.cropList.item(6).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All folder", None, -1))
        self.cropList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cropTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Crop Image", None, -1))
        __sortingEnabled = self.generateList.isSortingEnabled()
        self.generateList.setSortingEnabled(False)
        self.generateList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Config", None, -1))
        self.generateList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Apply", None, -1))
        self.generateList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Save", None, -1))
        self.generateList.item(3).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All Folder", None, -1))
        self.generateList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generateTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Generate", None, -1))
        __sortingEnabled = self.superResolutionList.isSortingEnabled()
        self.superResolutionList.setSortingEnabled(False)
        self.superResolutionList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Config", None, -1))
        self.superResolutionList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Apply", None, -1))
        self.superResolutionList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Reset", None, -1))
        self.superResolutionList.item(3).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Save", None, -1))
        self.superResolutionList.item(4).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All Folder", None, -1))
        self.superResolutionList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.superResolutionTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Super resolution", None, -1))
        __sortingEnabled = self.segmentList.isSortingEnabled()
        self.segmentList.setSortingEnabled(False)
        self.segmentList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Config", None, -1))
        self.segmentList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Apply", None, -1))
        self.segmentList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Reset", None, -1))
        self.segmentList.item(3).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Save", None, -1))
        self.segmentList.item(4).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All Folder", None, -1))
        self.segmentList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SegmentTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Segmentation", None, -1))
        __sortingEnabled = self.evaluateList.isSortingEnabled()
        self.evaluateList.setSortingEnabled(False)
        self.evaluateList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Config", None, -1))
        self.evaluateList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Apply", None, -1))
        self.evaluateList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Reset", None, -1))
        self.evaluateList.item(3).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Save", None, -1))
        self.evaluateList.item(4).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All Folder", None, -1))
        self.evaluateList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.evaluateTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Evaluate SR", None, -1))
        __sortingEnabled = self.cleanlinessList.isSortingEnabled()
        self.cleanlinessList.setSortingEnabled(False)
        self.cleanlinessList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Config", None, -1))
        self.cleanlinessList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Apply", None, -1))
        self.cleanlinessList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Reset", None, -1))
        self.cleanlinessList.item(3).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Save", None, -1))
        self.cleanlinessList.item(4).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All Folder", None, -1))
        self.cleanlinessList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cleanlinessTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Cleanliness Check", None, -1))
        __sortingEnabled = self.dicomList.isSortingEnabled()
        self.dicomList.setSortingEnabled(False)
        self.dicomList.item(0).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Meta Data", None, -1))
        self.dicomList.item(1).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Export", None, -1))
        self.dicomList.item(2).setText(QtWidgets.QApplication.translate("Cleanliness_Check", "All Folder", None, -1))
        self.dicomList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dicomTab), QtWidgets.QApplication.translate("Cleanliness_Check", "Export DICOM", None, -1))
        self.SR2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "2", None, -1))
        self.SR4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "4", None, -1))
        self.SR8.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "8", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Evaluate", None, -1))
        self.worstx2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "1 Worst", None, -1))
        self.poorx2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "2 Poor", None, -1))
        self.goodx2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "3 Good", None, -1))
        self.betterx2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "4 Better", None, -1))
        self.excellentx2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "5 Excellent", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Description", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Evaluate", None, -1))
        self.worstx4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "1 Worst", None, -1))
        self.poorx4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "2 Poor", None, -1))
        self.goodx4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "3 Good", None, -1))
        self.betterx4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "4 Better", None, -1))
        self.excellentx4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "5 Excellent", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Description", None, -1))
        self.btnNextx4.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Next", None, -1))
        self.sourceImage.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "Source Image", None, -1))
        self.destinationImage.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "x2", None, -1))
        self.destinationImage_2.setText(QtWidgets.QApplication.translate("Cleanliness_Check", "x4", None, -1))

import resources_rc
